/*
* FileSaver.js
* A saveAs() FileSaver implementation.
*
* By Eli Grey, http://eligrey.com
*
* License : https://github.com/eligrey/FileSaver.js/blob/master/LICENSE.md (MIT)
* source  : http://purl.eligrey.com/github/FileSaver.js
*/
var _global=typeof window==="object"&&window.window===window?window:typeof self==="object"&&self.self===self?self:typeof global==="object"&&global.global===global?global:this;function bom(e,o){if(typeof o==="undefined")o={autoBom:false};else if(typeof o!=="object"){console.warn("Depricated: Expected third argument to be a object");o={autoBom:!o}}if(o.autoBom&&/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(e.type)){return new Blob([String.fromCharCode(65279),e],{type:e.type})}return e}function download(e,o,t){var n=new XMLHttpRequest;n.open("GET",e);n.responseType="blob";n.onload=function(){saveAs(n.response,o,t)};n.onerror=function(){console.error("could not download file")};n.send()}function corsEnabled(e){var o=new XMLHttpRequest;o.open("HEAD",e,false);o.send();return o.status>=200&&o.status<=299}function click(e){try{e.dispatchEvent(new MouseEvent("click"))}catch(t){var o=document.createEvent("MouseEvents");o.initMouseEvent("click",true,true,window,0,0,0,80,20,false,false,false,false,0,null);e.dispatchEvent(o)}}var saveAs=_global.saveAs||(typeof window!=="object"||window!==_global)?function e(){}:"download"in HTMLAnchorElement.prototype?function e(o,t,n){var a=_global.URL||_global.webkitURL;var l=document.createElement("a");t=t||o.name||"download";l.download=t;l.rel="noopener";if(typeof o==="string"){l.href=o;if(l.origin!==location.origin){corsEnabled(l.href)?download(o,t,n):click(l,l.target="_blank")}else{click(l)}}else{l.href=a.createObjectURL(o);setTimeout(function(){a.revokeObjectURL(l.href)},4e4);setTimeout(function(){click(l)},0)}}:"msSaveOrOpenBlob"in navigator?function e(o,t,n){t=t||o.name||"download";if(typeof o==="string"){if(corsEnabled(o)){download(o,t,n)}else{var a=document.createElement("a");a.href=o;a.target="_blank";setTimeout(function(){click(a)})}}else{navigator.msSaveOrOpenBlob(bom(o,n),t)}}:function e(o,t,n,a){a=a||open("","_blank");if(a){a.document.title=a.document.body.innerText="downloading..."}if(typeof o==="string")return download(o,t,n);var l=o.type==="application/octet-stream";var i=/constructor/i.test(_global.HTMLElement)||_global.safari;var r=/CriOS\/[\d]+/.test(navigator.userAgent);if((r||l&&i)&&typeof FileReader==="object"){var s=new FileReader;s.onloadend=function(){var e=s.result;e=r?e:e.replace(/^data:[^;]*;/,"data:attachment/file;");if(a)a.location.href=e;else location=e;a=null};s.readAsDataURL(o)}else{var c=_global.URL||_global.webkitURL;var f=c.createObjectURL(o);if(a)a.location=f;else location.href=f;a=null;setTimeout(function(){c.revokeObjectURL(f)},4e4)}};_global.saveAs=saveAs.saveAs=saveAs;if(typeof module!=="undefined"){module.exports=saveAs}